server:
  port: 8081
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsh_erp?serverTimezone=UTC&characterEncoding=utf-8